### PR TITLE
Design Improvements, Content Updates, Black Spaces Removed and much more

### PR DESCRIPTION
**Pull request by SethuSenthil**

### CODE REVIEW

**Comment by shivanmodha** [comment]
image

this just completely made my day xD

Also for `Common CSS Libraries` [uikit](https://getuikit.com/) is on the rise

Otherwise, love the updates!

**Comment by SethuSenthil** [comment]
> image
> 
> this just completely made my day xD
> 
> Also for `Common CSS Libraries` [uikit](https://getuikit.com/) is on the rise
> 
> Otherwise, love the updates!

Lmao, VS Code is where it's at! Oh yeah, UI kit is amazing idk how I forgot

**Comment by shivanmodha** [comment]
I was considering integrating [this](https://github.com/Microsoft/monaco-editor) in the website for code examples at the end of last year, but never got around to it (and never found a good enough justification to implement this monster). It looks like a lot of work to integrate tho https://github.com/Microsoft/monaco-editor/issues/583. Maybe an update to the underlying react code and a major compilation update.

**Comment by SethuSenthil** [comment]
Wow! That's literally vs code on the web! PWA's have a rep of being worse than their native app equivalents, but this feels "native". I'm totally down to implement this, but is the site made with react? It's broken down into components, but it doesn't feel like _the react._ I don't get how the .json files are being utilized without any further compilation.

**Comment by SethuSenthil** [comment]
Have you heard about [code sandbox](https://codesandbox.io/)? It integrates with GitHub and it's easy as embedding a youtube video.

**Comment by shivanmodha** [comment]
This site was indeed made in react. It functions as a framework, which reads json configuration files for modularity. The goal is that you can update the website without ever having to know react, or recompile the entire website, making it easy to maintain. I actually use this framework for other things as well, because it makes it really easy to create a website without having to create a new react app with node and the nuances of starting a static web page from scratch. Also code sandbox is a good find, you guys should definitely use it

**Pull request merged**
